spring:
  application:
    name: service.zuul
    
server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


##设置feign调用的超时时间
ribbon:
 ##请求处理的超时时间
 ReadTimeout: 7000
 ##请求连接的超时时间
 ConnectTimeout: 5000
 
 
##禁用hystrix的超时时间，不过一般情况下不需要禁用，稍微延长超时时间就行
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
##开启zuul网关
zuul:
  routes:
    member:
      path: /service-member/**
      url: service.member

       

