spring:
  application:
    name: order
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/wucstone?autoReconnect=true&characterEncoding=utf8
    test-on-borrow: true
    validation-interval: 3600000
    validation-query: SELECT 1
    tomcat:
      initial-size: 100
      max-active: 200



server:
  port: 8763
  
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


##设置feign调用的超时时间
ribbon:
 ##请求处理的超时时间
 ReadTimeout: 7000
 ##请求连接的超时时间
 ConnectTimeout: 5000
 
##开启hystrix断路器
feign:
 hystrix:
  enabled: true
  
##禁用hystrix的超时时间，不过一般情况下不需要禁用，稍微延长超时时间就行
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
