spring:
  application:
    name: order


server:
  port: 8763
  
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/


##设置feign调用的超时时间
ribbon:
 ##请求处理的超时时间
 ReadTimeout: 7000
 ##请求连接的超时时间
 ConnectTimeout: 5000
 
##开启hystrix断路器
feign:
 hystrix:
  enabled: true
  
##禁用hystrix的超时时间，不过一般情况下不需要禁用，稍微延长超时时间就行
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

sharding:
  jdbc:
    datasource:
      names: ds_0
      ds_0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://192.168.244.100:3306/huihua_saas_demo?autoReconnect=true&characterEncoding=utf8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: true
        validation-interval: 3600000
        validation-query: SELECT 1
        test-while-idle: true